//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP.Activity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int Id { get; set; }
        public int reg { get; set; }
        public int timeslot { get; set; }
        public int user { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Period Period { get; set; }
    }
}
